### PR TITLE
Fixes some typos

### PR DESCRIPTION
**Pull request by grunch**

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Thank you! Asked @UkolovaOlga who is maintaining this repo to review and merge

**Review by dr-orlovsky — APPROVED** [review]

**Review by UkolovaOlga — COMMENTED** [review]
Thank you for your contribution!
Do I understand correctly that you fixed a couple of typos and spaces between the lines/abstracts on some pages?

**Comment by grunch** [comment]
> Thank you for your contribution! Do I understand correctly that you fixed a couple of typos and spaces between the lines/abstracts on some pages?

Hi Olga, yes exactly

**Comment by aljazceru** [comment]
please merge this, the first thing i did after reading the faq was coming here to open a PR with the typos :)

**Pull request merged**
